# Jeremy's preferred prompt
PS1='\[\e[01;32m\]\A\[\e[00m\]:\[\e[01;34m\]\W\[\e[00m\] \$ '

alias yt-dlp='~/Downloads/venv/bin/yt-dlp'
alias yt-audio='yt-dlp -f 140 --split-chapters -o "chapter:%(title)s/%(section_number)02d - %(section_title)s.%(ext)s"'

alias vlc-folder='vlc -Zf --recursive expand'
