let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'pangloss/vim-javascript'
Plug 'othree/html5.vim'

Plug 'sheerun/vim-polyglot'

Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'scrooloose/nerdcommenter'
Plug 'airblade/vim-gitgutter'
call plug#end()

let g:coc_global_extensions = [ 'coc-json', 'coc-tsserver' ]

" Indentation
filetype plugin indent on
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2

set nowrap
set number
set ruler

set mouse=a

" Mitigating visual glitches
set nolazyredraw
nnoremap <F5> :syntax sync fromstart

" Make Ctrl+Backspace and Ctrl+Delete remove whole words
imap <C-BS> <C-w>
imap <C-Del> <Esc>ldWi

" Use CTRL-S for saving, also in Insert mode
noremap <silent> <C-S> :update<CR>
vnoremap <silent> <C-S> <C-C>:update<CR>
inoremap <silent> <C-S> <C-O>:update<CR>
